wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.11
    cli_version: 0.23.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1764897810
    t:
      1:
      - 1
      - 41
      - 48
      2:
      - 1
      - 41
      - 48
      3:
      - 2
      - 4
      - 13
      - 15
      - 16
      - 42
      4: 3.12.11
      5: 0.23.1
      8:
      - 2
      13: linux-x86_64
    e:
      r6b0kbntrqdbudzpzm2vh9cvgxhra8ti:
        os: Linux-6.8.0-1024-aws-x86_64-with-glibc2.39
        python: CPython 3.12.11
        started_at: '2025-12-05T01:23:30.240809Z'
        args:
        - --lr_g
        - '0.0002'
        - --lr_d
        - '0.00005'
        - --batchsize
        - '6'
        - --epochs
        - '300'
        - --num_workers
        - '4'
        program: /teamspace/studios/this_studio/medical-I2I-benchmark/scripts/pix2pix_t1t2.py
        code_path: scripts/pix2pix_t1t2.py
        code_path_local: scripts/pix2pix_t1t2.py
        git:
          remote_url: https://github.com/Shreyas-prog108/medical-I2I-benchmark.git
          commit: 8e592a6993dd0e52f44b95fab4d55fcd0fc2860d
        root: /teamspace/studios/this_studio/medical-I2I-benchmark
        host: ip-10-192-10-245
        executable: /home/zeus/miniconda3/envs/cloudspace/bin/python
        cpu_count: 2
        cpu_count_logical: 4
        gpu_type: Tesla T4
        gpu_count: 1
        disk:
          /:
            total: '244936478720'
            used: '87259324416'
        memory:
          total: '16555139072'
        gpu_nvidia:
        - name: Tesla T4
          memory_total: '16106127360'
          cuda_cores: 2560
          architecture: Turing
          uuid: GPU-9dbdba84-71b2-0597-7b34-55d88b66b29a
        cuda_version: '12.8'
        writer_id: r6b0kbntrqdbudzpzm2vh9cvgxhra8ti
modelG:
  desc: null
  value: UNetGenerator2D
modelD:
  desc: null
  value: NLayerDiscriminator2D
epochs:
  desc: null
  value: 300
n_epochs_decay:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 6
num_workers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: Adam
learning_rate_g:
  desc: null
  value: 0.0002
learning_rate_d:
  desc: null
  value: 5.0e-05
beta1:
  desc: null
  value: 0.5
lambda_l1:
  desc: null
  value: 100.0
loss_functions:
  desc: null
  value: BCEWithLogitsLoss, L1Loss
device:
  desc: null
  value: Tesla T4
